export default {
  name: 'project',
  title: 'Projects',
  type: 'document',
  groups: [
    { name: 'basic', title: 'Basic Info' },
    { name: 'details', title: 'Project Details' },
    { name: 'description', title: 'Description' },
    { name: 'media', title: 'Photos & Media' },
    { name: 'seo', title: 'SEO' },
  ],
  fields: [
    {
      name: 'title',
      title: 'Project Title',
      type: 'string',
      group: 'basic',
      validation: (Rule: any) => Rule.required(),
      description: 'e.g., "Modern Kitchen Renovation"',
    },
    {
      name: 'slug',
      title: 'Slug (URL)',
      type: 'slug',
      options: { source: 'title', maxLength: 96 },
      group: 'basic',
      validation: (Rule: any) => Rule.required(),
    },
    {
      name: 'status',
      title: 'Status',
      type: 'string',
      group: 'basic',
      options: {
        list: [
          { title: 'Completed', value: 'completed' },
          { title: 'In Progress', value: 'in-progress' },
          { title: 'Upcoming', value: 'upcoming' },
        ],
        layout: 'radio',
      },
      initialValue: 'completed',
    },
    {
      name: 'projectType',
      title: 'Project Type',
      type: 'string',
      group: 'basic',
      description: 'e.g., Kitchen Remodel, Bathroom, Addition, Full Renovation',
    },
    {
      name: 'service',
      title: 'Service Category',
      type: 'reference',
      to: [{ type: 'service' }],
      group: 'basic',
    },
    {
      name: 'location',
      title: 'Location',
      type: 'object',
      group: 'basic',
      fields: [
        { name: 'city', title: 'City', type: 'string' },
        { name: 'state', title: 'State', type: 'string' },
        { name: 'neighborhood', title: 'Neighborhood/Area', type: 'string' },
      ],
    },
    {
      name: 'completionDate',
      title: 'Completion Date',
      type: 'date',
      group: 'details',
    },
    {
      name: 'duration',
      title: 'Project Duration',
      type: 'string',
      group: 'details',
      description: 'e.g., "6 weeks", "3 months"',
    },
    {
      name: 'budgetRange',
      title: 'Budget Range',
      type: 'string',
      group: 'details',
      description: 'e.g., "$50,000 - $75,000" or "$" or leave empty',
    },
    {
      name: 'scope',
      title: 'Scope of Work',
      type: 'array',
      of: [{ type: 'string' }],
      group: 'details',
      description: 'List items: "Demo existing kitchen", "Custom cabinetry", etc.',
    },
    {
      name: 'permitNumber',
      title: 'Permit Number',
      type: 'string',
      group: 'details',
      description: 'Optional - building permit reference',
    },
    {
      name: 'shortDescription',
      title: 'Short Description',
      type: 'text',
      rows: 3,
      group: 'description',
      description: 'Brief summary for project cards',
    },
    {
      name: 'description',
      title: 'Full Description',
      type: 'text',
      rows: 10,
      group: 'description',
      description: 'Detailed project story. Use double line breaks for paragraphs.',
    },
    {
      name: 'clientTestimonial',
      title: 'Client Testimonial (for this project)',
      type: 'text',
      rows: 4,
      group: 'description',
    },
    {
      name: 'clientName',
      title: 'Client Name (for testimonial)',
      type: 'string',
      group: 'description',
    },
    {
      name: 'heroImage',
      title: 'Main Image (After)',
      type: 'image',
      options: { hotspot: true },
      group: 'media',
      validation: (Rule: any) => Rule.required(),
    },
    {
      name: 'beforeImage',
      title: 'Before Image',
      type: 'image',
      options: { hotspot: true },
      group: 'media',
    },
    {
      name: 'gallery',
      title: 'Photo Gallery',
      type: 'array',
      of: [
        {
          type: 'image',
          options: { hotspot: true },
          fields: [
            { name: 'alt', title: 'Alt Text', type: 'string' },
            { name: 'caption', title: 'Caption', type: 'string' },
          ],
        },
      ],
      group: 'media',
    },
    {
      name: 'videoUrl',
      title: 'Video URL',
      type: 'url',
      group: 'media',
      description: 'YouTube or Vimeo URL (optional)',
    },
    {
      name: 'seoTitle',
      title: 'SEO Title',
      type: 'string',
      group: 'seo',
    },
    {
      name: 'seoDescription',
      title: 'SEO Description',
      type: 'text',
      rows: 2,
      group: 'seo',
    },
  ],
  preview: {
    select: {
      title: 'title',
      status: 'status',
      media: 'heroImage',
    },
    prepare({ title, status, media }: any) {
      const icons: any = {
        'completed': '✅',
        'in-progress': '🔨',
        'upcoming': '📋',
      }
      return {
        title,
        subtitle: `${icons[status] || ''} ${status}`,
        media,
      }
    },
  },
}
